baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
baseURL: "https://naga.network/"
languageCode: en-us
title: NAGA ELECTRIC INDUSTRIAL CO., LTD.
theme: PaperMod
params:
  defaultTheme: dark
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: "NAGA ELECTRIC INDUSTRIAL CO., LTD."
    subtitle: "CELESTIAL INTERFACE PROJECT → DREAMLINE ELECTRICAL CONSCIOUSNESS CORE"
  customCSS:
    - css/naga.css
menu:
  main:
    - name: Operator File
      url: /operator-file/
      weight: 10
    - name: Operational History
      url: /operational-history/
      weight: 20
    - name: Project Manifest
      url: /project-manifest/
      weight: 30
    - name: Core Directive
      url: /core-directive/
      weight: 40
markup:
  goldmark:
    renderer:
      unsafe: true